nelmio_api_doc:
    documentation:
        info:
            title: Study-on billing
            description:
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/api/v1/login
            - ^/api/v1/register
