app.swagger_ui:
  path: /api/v1/doc
  methods: GET
  defaults: { _controller: nelmio_api_doc.controller.swagger_ui }

login_check:
  path: /api/v1/login
  methods: POST


register:
  path: /api/v1/register
  controller: App\Controller\ApiController:register
  methods: POST


